---
name: Post release ✨

on:
  release:
    types: ["released"]

jobs:
  vbump:
    name: Version Bump 🤜🤛
    uses: ./.github/workflows/version-bump.yaml
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      vbump-after-release: true
